# NEWS CLASSIFICATION

In [113]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

### The Dataset : NewsDataset.json

In [3]:
allNews = pd.read_json('NewsDataset.json',lines=True)

In [4]:
allNews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200853 entries, 0 to 200852
Data columns (total 6 columns):
authors              200853 non-null object
category             200853 non-null object
date                 200853 non-null datetime64[ns]
headline             200853 non-null object
link                 200853 non-null object
short_description    200853 non-null object
dtypes: datetime64[ns](1), object(5)
memory usage: 9.2+ MB


In [5]:
allNews.head()

authors       category       date  \
0  Melissa Jeltsen          CRIME 2018-05-26   
1    Andy McDonald  ENTERTAINMENT 2018-05-26   
2       Ron Dicker  ENTERTAINMENT 2018-05-26   
3       Ron Dicker  ENTERTAINMENT 2018-05-26   
4       Ron Dicker  ENTERTAINMENT 2018-05-26   

                                            headline  \
0  There Were 2 Mass Shootings In Texas Last Week...   
1  Will Smith Joins Diplo And Nicky Jam For The 2...   
2    Hugh Grant Marries For The First Time At Age 57   
3  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  Julianna Margulies Uses Donald Trump Poop Bags...   

                                                link  \
0  https://www.huffingtonpost.com/entry/texas-ama...   
1  https://www.huffingtonpost.com/entry/will-smit...   
2  https://www.huffingtonpost.com/entry/hugh-gran...   
3  https://www.huffingtonpost.com/entry/jim-carre...   
4  https://www.huffingtonpost.com/entry/julianna-...   

                                   short_description  
0  She left her husband. He killed their children...  
1                           Of course it has a song.  
2  The actor and his longtime girlfriend Anna Ebe...  
3  The actor gives Dems an ass-kicking for not fi...  
4  The "Dietland" actress said using the bags is ...

In [8]:
allNews.describe()

authors  category                 date        headline  \
count   200853    200853               200853          200853   
unique   27993        41                 2309          199344   
top             POLITICS  2013-01-17 00:00:00  Sunday Roundup   
freq     36620     32739                  100              90   
first      NaN       NaN  2012-01-28 00:00:00             NaN   
last       NaN       NaN  2018-05-26 00:00:00             NaN   

                                                     link short_description  
count                                              200853            200853  
unique                                             200812            178353  
top     https://www.huffingtonpost.comhttp://www.mothe...                    
freq                                                    2             19712  
first                                                 NaN               NaN  
last                                                  NaN               NaN

#### Dropping The Unwanted Features from the dataset

In [6]:
droplist=['authors','date','link']
for todrop in droplist:
    allNews = allNews.drop(todrop,1)

In [10]:
allNews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200853 entries, 0 to 200852
Data columns (total 3 columns):
category             200853 non-null object
headline             200853 non-null object
short_description    200853 non-null object
dtypes: object(3)
memory usage: 4.6+ MB


In [11]:
allNews.head()

category                                           headline  \
0          CRIME  There Were 2 Mass Shootings In Texas Last Week...   
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   

                                   short_description  
0  She left her husband. He killed their children...  
1                           Of course it has a song.  
2  The actor and his longtime girlfriend Anna Ebe...  
3  The actor gives Dems an ass-kicking for not fi...  
4  The "Dietland" actress said using the bags is ...

In [12]:
allNews.columns

Index(['category', 'headline', 'short_description'], dtype='object')

In [8]:
allNews.columns=['CATEGORY','TITLE','DESC']

In [14]:
allNews.head()

CATEGORY                                              TITLE  \
0          CRIME  There Were 2 Mass Shootings In Texas Last Week...   
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   

                                                DESC  
0  She left her husband. He killed their children...  
1                           Of course it has a song.  
2  The actor and his longtime girlfriend Anna Ebe...  
3  The actor gives Dems an ass-kicking for not fi...  
4  The "Dietland" actress said using the bags is ...

In [15]:
allNews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200853 entries, 0 to 200852
Data columns (total 3 columns):
CATEGORY    200853 non-null object
TITLE       200853 non-null object
DESC        200853 non-null object
dtypes: object(3)
memory usage: 4.6+ MB


In [9]:
labels_of_news=[]
x = allNews['CATEGORY'].value_counts()
for i in x.index:
    labels_of_news.append(i)

In [17]:
allNews['CATEGORY'].value_counts()

POLITICS          32739
WELLNESS          17827
ENTERTAINMENT     16058
TRAVEL             9887
STYLE & BEAUTY     9649
PARENTING          8677
HEALTHY LIVING     6694
QUEER VOICES       6314
FOOD & DRINK       6226
BUSINESS           5937
COMEDY             5175
SPORTS             4884
BLACK VOICES       4528
HOME & LIVING      4195
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3651
WOMEN              3490
IMPACT             3459
DIVORCE            3426
CRIME              3405
MEDIA              2815
WEIRD NEWS         2670
GREEN              2622
WORLDPOST          2579
RELIGION           2556
STYLE              2254
SCIENCE            2178
WORLD NEWS         2177
TASTE              2096
TECH               2082
MONEY              1707
ARTS               1509
FIFTY              1401
GOOD NEWS          1398
ARTS & CULTURE     1339
ENVIRONMENT        1323
COLLEGE            1144
LATINO VOICES      1129
CULTURE & ARTS     1030
EDUCATION          1004
Name: CATEGORY, 

In [18]:
print("value_counts",len(allNews['CATEGORY'].value_counts()))
print("label_of_news",len(labels_of_news))

value_counts 41
label_of_news 41


In [19]:
labels_of_news

['POLITICS',
 'WELLNESS',
 'ENTERTAINMENT',
 'TRAVEL',
 'STYLE & BEAUTY',
 'PARENTING',
 'HEALTHY LIVING',
 'QUEER VOICES',
 'FOOD & DRINK',
 'BUSINESS',
 'COMEDY',
 'SPORTS',
 'BLACK VOICES',
 'HOME & LIVING',
 'PARENTS',
 'THE WORLDPOST',
 'WEDDINGS',
 'WOMEN',
 'IMPACT',
 'DIVORCE',
 'CRIME',
 'MEDIA',
 'WEIRD NEWS',
 'GREEN',
 'WORLDPOST',
 'RELIGION',
 'STYLE',
 'SCIENCE',
 'WORLD NEWS',
 'TASTE',
 'TECH',
 'MONEY',
 'ARTS',
 'FIFTY',
 'GOOD NEWS',
 'ARTS & CULTURE',
 'ENVIRONMENT',
 'COLLEGE',
 'LATINO VOICES',
 'CULTURE & ARTS',
 'EDUCATION']

- Checking the category and their title and description

In [20]:
wellness = allNews.loc[allNews['CATEGORY'] == "WELLNESS"]
wellness.head() #Remove it 

CATEGORY                                              TITLE  \
124989  WELLNESS                Why Overeating Doesn't Make You Fat   
124990  WELLNESS  14 Habits Of People With A Healthy Relationshi...   
124993  WELLNESS           5 Things That Could Be Stealing Your Joy   
124994  WELLNESS                                Moments Make a Life   
124996  WELLNESS                                          Fat Facts   

                                                     DESC  
124989  If you take the right approach to ending your ...  
124990  After a long list of rules and habits like the...  
124993  Listen to yourself all day today -- are you an...  
124994  Consciously constructing positive habits -- or...  
124996  Human fat cells, photo by Dr. Peeke Here's how...

In [21]:
parent =  allNews.loc[allNews['CATEGORY'] == "PARENTS"]
parent.head() # remove it 


CATEGORY                                              TITLE  \
6194  PARENTS        40 Tweets That Sum Up Life With 4-Year-Olds   
6524  PARENTS  These Were The Trendiest Baby Names In The Lat...   
6625  PARENTS  These Quotes From Kids Are Hilarious, Adorable...   
6848  PARENTS  30 'Star Wars'-Inspired Names Parents Are Givi...   
6955  PARENTS  Parents Are Honoring Their Favorite Musicians ...   

                                                   DESC  
6194  "Hell hath no fury like a 4yo whose apple slic...  
6524  Shout out to the Jessicas and Ambers of the wo...  
6625  "Mommy, this song sounds a lot like the McDonn...  
6848     Get ready to meet some more Kylos and Anakins.  
6955        From Wilco and Beyonce to Jagger and Bowie.

In [22]:
env =  allNews.loc[allNews['CATEGORY'] == "ENVIRONMENT"]
env.head() # merge with ENTERTAINMENT

CATEGORY                                              TITLE  \
125421  ENVIRONMENT  Sky Vets Perform Incredible Rescue To Save Wil...   
125422  ENVIRONMENT  Animal Photos Of The Week: Baby Panda Goes For...   
125423  ENVIRONMENT  Washington Mudslide Menacing Fabled Pacific No...   
125424  ENVIRONMENT  America's Exotic Pet Obsession Is Out Of Contr...   
125494  ENVIRONMENT             Time to Leave Our Bad Carbon Boyfriend   

                                                     DESC  
125421  Warning: This video contains graphic images of...  
125422  This week has been an interesting one in the w...  
125423  The tribe - whose name means "the river people...  
125424  Nearly two-thirds of Americans own at least on...  
125494  But break-ups happen all the time and we find ...

In [23]:
divorce =  allNews.loc[allNews['CATEGORY'] == "DIVORCE"]
divorce.head() # remove it 

CATEGORY                                              TITLE  \
125009  DIVORCE  50 Empowering Songs To Help Get You Through A ...   
125012  DIVORCE  I'm Sleeping With A Cheater, Only Complicating...   
125022  DIVORCE  Blake And Miranda Respond To Divorce Rumors In...   
125028  DIVORCE  What 'Grey's Anatomy' Taught Me About Moving O...   
125043  DIVORCE  How to Revitalize Love and Passion With Your P...   

                                                     DESC  
125009  Breakups are a very special and pointed type o...  
125012  I’ve been a sex worker for six years–my entire...  
125022  Worried about the state of Blake Shelton and M...  
125028  If there's ever a time you need a little distr...  
125043  Let's face it, when we fall in love and commit...

In [24]:
taste =  allNews.loc[allNews['CATEGORY'] == "TASTE"]
taste.head() # remove it

CATEGORY                                              TITLE  \
7499    TASTE  It's Weird That American Restaurants Serve Ice...   
7568    TASTE  Pineapple Casserole, The Southern Dish That's ...   
7842    TASTE        How To Actually Get A Bartender's Attention   
7925    TASTE  Diet Coke's Millennial-Inspired Makeover Leave...   
8102    TASTE  We Tested The New 'Tearless' Onions To See If ...   

                                                   DESC  
7499  But why do we even have ice in our drinks in t...  
7568  It's got pineapple, cheddar and a whole lot of...  
7842              Plus other things they wish you knew.  
7925    It's not like a regular soda, it's a cool soda.  
8102                     Put away your goggles, people.

In [25]:
impact =  allNews.loc[allNews['CATEGORY'] == "IMPACT"]
impact.head() # remove it

CATEGORY                                              TITLE  \
12    IMPACT  With Its Way Of Life At Risk, This Remote Oyst...   
66    IMPACT  Monsanto And Bayer Are Set To Merge. Here's Wh...   
125   IMPACT  You're Going To Use That Self-Checkout Machine...   
193   IMPACT  Machines Don't Always Steal Our Jobs. Increasi...   
286   IMPACT  She Started A Suicide Prevention Site At Age 1...   

                                                  DESC  
12    The revolution is coming to rural New Brunswick.  
66   “Together they will influence markets all over...  
125  We may not realize it, but retailers are condi...  
193               Your next boss could be an algorithm  
286  “People didn’t view me seriously because I was...

In [26]:
# WEDDINGS
wed =  allNews.loc[allNews['CATEGORY'] == "WEDDINGS"]
wed.head() # remove it

CATEGORY                                              TITLE  \
125013  WEDDINGS  This Wedding Guest Is The Cutest Little Thief ...   
125023  WEDDINGS  Girls Are Already Lining Up To Marry Prince Ge...   
125045  WEDDINGS  Wedding Party Reenacts Leonardo da Vinci's 'La...   
125049  WEDDINGS            The Ultimate Spring Wedding Inspiration   
125077  WEDDINGS                         The Case for Separate Beds   

                                                     DESC  
125013  We're onto you, little one. [H/T Reddit user b...  
125023  Keep in touch! Check out HuffPost Weddings on ...  
125045  "Everyone was great and went with it because t...  
125049  Check out these inspirational photos to make y...  
125077  The other night I slept on a twin bed in the g...

In [27]:
for i in labels_of_news:   
    print("----------------------------------------------------------------------------------------------------")

    print("----------------------------------------------------------------------------------------------------")
    print(allNews.loc[allNews['CATEGORY'] == i].head())
    print("----------------------------------------------------------------------------------------------------")
    print("----------------------------------------------------------------------------------------------------")


----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
    CATEGORY                                              TITLE  \
13  POLITICS  Trump's Crackdown On Immigrant Parents Puts Mo...   
14  POLITICS  'Trump's Son Should Be Concerned': FBI Obtaine...   
15  POLITICS  Edward Snowden: There's No One Trump Loves Mor...   
16  POLITICS  Booyah: Obama Photographer Hilariously Trolls ...   
17  POLITICS  Ireland Votes To Repeal Abortion Amendment In ...   

                                                 DESC  
13  Last month a Health and Human Services officia...  
14  The wiretaps feature conversations between Ale...  
15  But don't count on Robert Mueller to nail him,...  
16                             Just a peeping minute.  
17  Irish women will no longer have to travel to t...  
-----------------------------------------------------------

132  West Hollywood has also reaffirmed its commitm...  
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
            CATEGORY                                              TITLE  \
125019  FOOD & DRINK     Dallas Throws a Texas-size Wine and Food Party   
125026  FOOD & DRINK  We Tasted The New Fruit Punch Oreos, So You Do...   
125037  FOOD & DRINK  Yes, The Chia Seeds You Eat Are The Same Ones ...   
125046  FOOD & DRINK  Farm to Fork Across America: Chef Tom Douglas,...   
125059  FOOD & DRINK                                   The Whiskey Sour   

                                                     DESC  
125019                   Tex

        CATEGORY                                              TITLE  \
125013  WEDDINGS  This Wedding Guest Is The Cutest Little Thief ...   
125023  WEDDINGS  Girls Are Already Lining Up To Marry Prince Ge...   
125045  WEDDINGS  Wedding Party Reenacts Leonardo da Vinci's 'La...   
125049  WEDDINGS            The Ultimate Spring Wedding Inspiration   
125077  WEDDINGS                         The Case for Separate Beds   

                                                     DESC  
125013  We're onto you, little one. [H/T Reddit user b...  
125023  Keep in touch! Check out HuffPost Weddings on ...  
125045  "Everyone was great and went with it because t...  
125049  Check out these inspirational photos to make y...  
125077  The other night I slept on a twin bed in the g...  
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-----------

     CATEGORY                                              TITLE  \
7293    STYLE  Saoirse Ronan's Stunning Style Evolution Throu...   
7460    STYLE  Glossier Just Dropped Its First-Ever Solution ...   
7461    STYLE  More Models Come Forward To Accuse Bruce Weber...   
7476    STYLE  Here's Your 10-Piece Winter Capsule Wardrobe C...   
7542    STYLE  18 Valentine's Day Gifts For Him That Aren't R...   

                                                   DESC  
7293  The "Lady Bird" star has been killing it on th...  
7460                       Consider this your solution.  
7461  Some of the alleged incidents occurred more th...  
7476                       It's all about those layers.  
7542   You don’t have to get him something lovey-dovey.  
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-----------------------------------------

           CATEGORY                                              TITLE  \
125421  ENVIRONMENT  Sky Vets Perform Incredible Rescue To Save Wil...   
125422  ENVIRONMENT  Animal Photos Of The Week: Baby Panda Goes For...   
125423  ENVIRONMENT  Washington Mudslide Menacing Fabled Pacific No...   
125424  ENVIRONMENT  America's Exotic Pet Obsession Is Out Of Contr...   
125494  ENVIRONMENT             Time to Leave Our Bad Carbon Boyfriend   

                                                     DESC  
125421  Warning: This video contains graphic images of...  
125422  This week has been an interesting one in the w...  
125423  The tribe - whose name means "the river people...  
125424  Nearly two-thirds of Americans own at least on...  
125494  But break-ups happen all the time and we find ...  
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------

In [28]:
## Merging Categories


In [10]:
#worldpost and 'the worldpost'
allNews.CATEGORY = allNews.CATEGORY.map(lambda x: "WORLDPOST" if x == "THE WORLDPOST" else x)
allNews.CATEGORY = allNews.CATEGORY.map(lambda x: "ENTERTAINMENT" if x == "COMEDY" else x)
allNews.CATEGORY = allNews.CATEGORY.map(lambda x: "ARTS_CULTURE" if x == "ARTS" or x=="CULTURE & ARTS" or x=="ARTS & CULTURE" else x)


In [11]:
allNews.CATEGORY = allNews.CATEGORY.map(lambda x: "WORLDNEWS" if x == "WORLDPOST" or x == "WORLD NEWS"  else x)


In [12]:
len(allNews.CATEGORY.value_counts())

36

In [33]:
(allNews.CATEGORY.value_counts())

POLITICS          32739
ENTERTAINMENT     21233
WELLNESS          17827
TRAVEL             9887
STYLE & BEAUTY     9649
PARENTING          8677
WORLDNEWS          8420
HEALTHY LIVING     6694
QUEER VOICES       6314
FOOD & DRINK       6226
BUSINESS           5937
SPORTS             4884
BLACK VOICES       4528
HOME & LIVING      4195
PARENTS            3955
ARTS_CULTURE       3878
WEDDINGS           3651
WOMEN              3490
IMPACT             3459
DIVORCE            3426
CRIME              3405
MEDIA              2815
WEIRD NEWS         2670
GREEN              2622
RELIGION           2556
STYLE              2254
SCIENCE            2178
TASTE              2096
TECH               2082
MONEY              1707
FIFTY              1401
GOOD NEWS          1398
ENVIRONMENT        1323
COLLEGE            1144
LATINO VOICES      1129
EDUCATION          1004
Name: CATEGORY, dtype: int64

- ### NEEDED LABELS ONLY

In [13]:
final_category = ["POLITICS","ENTERTAINMENT","WORLDNEWS","SPORTS","BUSINESS","TECH","SCIENCE","ARTS_CULTURE"]
len(final_category)

8

In [14]:
myNewsDataset =  allNews.loc[allNews['CATEGORY'].isin(final_category)]
myNewsDataset.head()

CATEGORY                                              TITLE  \
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   
5  ENTERTAINMENT  Morgan Freeman 'Devastated' That Sexual Harass...   

                                                DESC  
1                           Of course it has a song.  
2  The actor and his longtime girlfriend Anna Ebe...  
3  The actor gives Dems an ass-kicking for not fi...  
4  The "Dietland" actress said using the bags is ...  
5  "It is not right to equate horrific incidents ...

In [15]:
myNewsDataset.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 81351 entries, 1 to 200852
Data columns (total 3 columns):
CATEGORY    81351 non-null object
TITLE       81351 non-null object
DESC        81351 non-null object
dtypes: object(3)
memory usage: 2.5+ MB


In [37]:
myNewsDataset.describe()

CATEGORY           TITLE   DESC
count      81351           81351  81351
unique         8           81041  70108
top     POLITICS  Sunday Roundup       
freq       32739              90  10430

In [38]:
myNewsDataset.CATEGORY.value_counts()

POLITICS         32739
ENTERTAINMENT    21233
WORLDNEWS         8420
BUSINESS          5937
SPORTS            4884
ARTS_CULTURE      3878
SCIENCE           2178
TECH              2082
Name: CATEGORY, dtype: int64

## More Work to DO 

In [16]:
myNewsDataset["data"]=myNewsDataset.TITLE + " " + myNewsDataset.DESC

/home/felladog/.local/share/virtualenvs/BreakFast-vYJ3fvFQ/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [17]:
droplist=['TITLE','DESC']
for todrop in droplist:
    myNewsDataset = myNewsDataset.drop(todrop,1)

In [41]:
myNewsDataset.head()

CATEGORY                                               data
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...
2  ENTERTAINMENT  Hugh Grant Marries For The First Time At Age 5...
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...
5  ENTERTAINMENT  Morgan Freeman 'Devastated' That Sexual Harass...

In [18]:
myNewsDataset['Category_label']  =myNewsDataset.CATEGORY.map({'POLITICS':0,
                            'ENTERTAINMENT':1,
                            'WORLDNEWS':2,         
                            'BUSINESS':3,          
                            'SPORTS':4,            
                            'ARTS_CULTURE':5,      
                            'SCIENCE':6,           
                            'TECH':7})

In [19]:
myNewsDataset.columns

Index(['CATEGORY', 'data', 'Category_label'], dtype='object')

In [20]:
n_array=myNewsDataset.as_matrix()
x_data =n_array[:,1]
y_label =n_array[:,2]
y_label = y_label.astype('int')

/home/felladog/.local/share/virtualenvs/BreakFast-vYJ3fvFQ/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [46]:
myNewsDataset.head()

CATEGORY                                               data  \
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT  Hugh Grant Marries For The First Time At Age 5...   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   
5  ENTERTAINMENT  Morgan Freeman 'Devastated' That Sexual Harass...   

   Category_label  
1               1  
2               1  
3               1  
4               1  
5               1

# Spliting The Dataset

In [ ]:
train_set,test_set = train_test_split(myNewsDataset,test_size=0.2,random_state=42)

In [ ]:
train_set.CATEGORY.value_counts()
# test_set.CATEGORY.value_counts()

In [35]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(myNewsDataset, myNewsDataset["Category_label"]):
    strat_train_set = myNewsDataset.iloc[train_index]
    strat_test_set = myNewsDataset.iloc[test_index]
strat_train_set.head()

CATEGORY                                               data  \
4149         POLITICS  Trump Gun Proposal Probably Won't Include Univ...   
101089  ENTERTAINMENT  Pamela Adlon From 'Louie' Will Have Her Own Show    
81516        POLITICS  Bernie Sanders: My Supporters Are 'Not Anti-Hi...   
29601        POLITICS  Trump, Syria, And The Basics Of Strategy The s...   
113311      WORLDNEWS                            3 Million and Counting    

        Category_label  
4149                 0  
101089               1  
81516                0  
29601                0  
113311               2

In [37]:
strat_test_set

CATEGORY                                               data  \
2602         POLITICS  Cambridge Analytica Whistleblower: 'Absolutely...   
91374        POLITICS  GOP Crowd Applauds Calling Immigrants Rats and...   
70252        POLITICS  Democrats Are Proving Samuel Alito and John Ro...   
80670            TECH  Everything You Need To Know About The Newest A...   
71953   ENTERTAINMENT  These 'Star Wars' Infomercials ARE The Deals Y...   
92404    ARTS_CULTURE  Soldiers, Superstars, Coachella and PTSD: For ...   
116458  ENTERTAINMENT          'Big Business IS The New Big Government'    
68382   ENTERTAINMENT  Advice Columnist Punked By 'Seinfeld' Plot Nee...   
24261        POLITICS  Two Americans Two Americans “testified” this w...   
195667  ENTERTAINMENT  'Carrie' Remake: Chloe Grace Moretz, Haley Ben...   
37670    ARTS_CULTURE  The Folk Art Paintings Keeping Obama’s Legacy ...   
69824        POLITICS  Martin O'Malley risks missing next Democratic ...   
15068   ENTERTAINMENT  RIP, Mr. Petty Music never really spoke to me,...   
172941         SPORTS  Notre Dame, USC Rivalry: 'Green Jersey Game,' ...   
57133        POLITICS  New Payday-Loan Rules Won’t Stop Predatory Len...   
54610        POLITICS  Thursday's Morning Email: Authorities Detain S...   
91963        BUSINESS  Women in Business: Monique Oxender, Chief Sust...   
73003            TECH  Here's What Happens On Google After A Mass Sho...   
30995         SCIENCE  Scientists Create 3D Fly-Through Map Of Space ...   
28053        POLITICS  Senate Democrats Introduce Bill To Completely ...   
85171   ENTERTAINMENT  Dave Chappelle Speaks Out About Comeback, Says...   
87849        POLITICS  Black Lives and Gun Violence When states fail ...   
20032       WORLDNEWS  Can We Reduce The Race To The Bottom... At The...   
14103   ENTERTAINMENT  'SNL' Finally Took On Harvey Weinstein -- But ...   
7909         POLITICS  Congressman Trolls Trump With Introduction Of ...   
54816          SPORTS  Caitlyn Jenner Graces The Cover Of Sports Illu...   
102403       POLITICS     Obama Kicks Off 2015 With Shave Ice In Hawaii    
62894            TECH  Critics Absolutely Love The Oculus Rift But so...   
90108    ARTS_CULTURE  The Magic of Taiko for American Audiences A fe...   
78983        BUSINESS  Gap CEO On Why Running Beats Stress "I get tha...   
...               ...                                                ...   
19286   ENTERTAINMENT  Jimmy Kimmel Reveals Son Needs Two More Open H...   
54984          SPORTS  John Oliver Rips Into All Things Related To Ol...   
81481            TECH  eHarmony Wants To Set You Up... With Your Next...   
43706        POLITICS  GOP Senator Denies Irish Investment Is Designe...   
89547   ENTERTAINMENT             'San Andreas' Kills At The Box Office    
196235         SPORTS  NCAA Tournament Scores, Live Updates: UNC, Cre...   
108406  ENTERTAINMENT  'SNL' Brings Back All Of Jim Carrey's Best Cha...   
172276       BUSINESS  10 Things The Fast Food Industry Doesn't Want ...   
25375       WORLDNEWS  Angela Merkel Is Merely Being Honest With U.S....   
77095        POLITICS  What Happens To Kids Who Accidentally Shoot Th...   
53072   ENTERTAINMENT  We Inflated Too Many Balloons And Now The RNC ...   
52856         SCIENCE  Watch A Year Flash Before Your Eyes From 1 Mil...   
25097       WORLDNEWS  Climate Change Drives Domestic Violence In Fij...   
5743    ENTERTAINMENT  Legendary Crooner Vic Damone Dead At 89 He was...   
55394          SPORTS  Brandon Ingram: 'I Can Be A Versatile Guy And ...   
29997   ENTERTAINMENT  Yara Shahidi Says 'Black-ish' Helped Her Embra...   
91251        BUSINESS  Warren Buffett Social Media Data Offer a Busin...   
81695   ENTERTAINMENT  Jimmy Kimmel's Rude Interviewer Proves Technol...   
49667   ENTERTAINMENT  Kanye West Reportedly Has Free Rein To Do What...   
27521        POLITICS  Elizabeth Warren On Workplace Sexism: 'Bill O'...   
79868   ENTERTAINMENT  'Homeland' Director Lesli Linka Glatte

In [ ]:
# strat_train_set == is our training set
# strat_test_set == test set

# CountVectorizer

In [38]:
from sklearn.feature_extraction.text import CountVectorizer


In [44]:
cvec = CountVectorizer(stop_words="english")
x_train_data = cvec.fit(strat_train_set.data)
x_train_transform = cvec.transform(strat_train_set.data)
#transform the x_test data as per CountVectorizer from x_train data
x_test_transform = cvec.transform(strat_test_set.data)

In [26]:
y_train = strat_train_set.Category_label
y_test = strat_test_set.Category_label


In [57]:
from sklearn.naive_bayes import MultinomialNB


In [51]:
NBmodel = MultinomialNB()
# fitting
NBmodel.fit(x_train_transform,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
#Predicting x_test set
y_pred_class = NBmodel.predict(x_test_transform)

NameError: name 'NBmodel' is not defined

In [53]:
for i,j in zip(y_pred_class,y_test):
    print(i," -------- ",j)

0  --------  0
0  --------  0
0  --------  0
3  --------  7
1  --------  1
1  --------  5
0  --------  1
1  --------  1
0  --------  0
1  --------  1
5  --------  5
0  --------  0
1  --------  1
4  --------  4
3  --------  0
2  --------  0
3  --------  3
0  --------  7
6  --------  6
0  --------  0
1  --------  1
0  --------  0
0  --------  2
1  --------  1
0  --------  0
4  --------  4
0  --------  0
0  --------  7
5  --------  5
3  --------  3
0  --------  0
2  --------  2
0  --------  0
0  --------  0
0  --------  0
4  --------  4
0  --------  0
0  --------  0
0  --------  1
3  --------  3
0  --------  0
3  --------  2
0  --------  0
1  --------  1
1  --------  6
3  --------  3
3  --------  3
7  --------  7
0  --------  0
1  --------  1
0  --------  3
1  --------  4
1  --------  1
0  --------  1
6  --------  6
1  --------  1
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  0
1  --------  1
2  --------  2
0  --------  0
0  --------  0
1  --------  1
0  -------

0  --------  2
0  --------  0
2  --------  2
1  --------  1
0  --------  2
2  --------  2
0  --------  0
1  --------  1
1  --------  1
0  --------  0
1  --------  1
1  --------  1
0  --------  0
2  --------  2
1  --------  1
0  --------  0
3  --------  3
1  --------  1
1  --------  1
6  --------  6
0  --------  0
1  --------  1
0  --------  0
1  --------  1
1  --------  1
0  --------  0
0  --------  0
2  --------  0
1  --------  7
1  --------  1
0  --------  0
2  --------  2
2  --------  2
2  --------  2
0  --------  0
1  --------  1
1  --------  1
4  --------  4
5  --------  5
2  --------  2
3  --------  3
5  --------  5
0  --------  0
0  --------  0
1  --------  1
1  --------  1
0  --------  0
1  --------  1
2  --------  2
4  --------  4
5  --------  5
0  --------  0
1  --------  5
2  --------  2
1  --------  5
0  --------  0
1  --------  1
0  --------  0
1  --------  1
1  --------  1
0  --------  0
1  --------  0
0  --------  0
0  --------  0
0  --------  1
2  --------  2
3  -------

0  --------  2
6  --------  6
0  --------  1
1  --------  1
0  --------  0
0  --------  0
1  --------  1
4  --------  4
1  --------  1
1  --------  1
4  --------  4
1  --------  1
1  --------  1
1  --------  1
1  --------  3
0  --------  0
5  --------  5
1  --------  4
3  --------  3
1  --------  1
0  --------  0
2  --------  2
0  --------  0
3  --------  6
6  --------  6
1  --------  7
1  --------  1
1  --------  1
0  --------  0
2  --------  2
0  --------  1
0  --------  2
1  --------  1
1  --------  1
0  --------  0
0  --------  0
4  --------  4
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
2  --------  2
5  --------  5
1  --------  1
4  --------  4
1  --------  1
0  --------  0
0  --------  0
2  --------  0
1  --------  0
5  --------  5
2  --------  2
4  --------  4
3  --------  2
0  --------  2
2  --------  2
2  --------  2
0  --------  0
1  --------  1
0  --------  0
0  --------  3
0  --------  0
0  --------  3
1  --------  6
1  --------  1
2  -------

2  --------  4
1  --------  1
1  --------  1
0  --------  0
2  --------  2
3  --------  3
1  --------  1
3  --------  3
3  --------  3
2  --------  2
1  --------  6
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  3
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  0
4  --------  4
1  --------  1
1  --------  1
1  --------  4
2  --------  2
0  --------  0
2  --------  2
1  --------  5
5  --------  5
4  --------  4
0  --------  0
1  --------  1
1  --------  1
0  --------  0
0  --------  0
0  --------  0
0  --------  0
3  --------  3
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  3
0  --------  0
0  --------  0
0  --------  0
1  --------  1
1  --------  1
4  --------  4
1  --------  1
1  --------  5
0  --------  0
5  --------  5
0  --------  0
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
0  --------  0
0  --------  0
1  --------  1
4  --------  4
6  --------  6
0  -------

2  --------  0
3  --------  0
0  --------  0
0  --------  0
1  --------  4
4  --------  4
2  --------  2
0  --------  0
1  --------  1
0  --------  0
1  --------  1
0  --------  0
2  --------  2
1  --------  1
2  --------  2
1  --------  0
4  --------  4
0  --------  0
1  --------  1
5  --------  5
2  --------  2
1  --------  1
3  --------  3
2  --------  3
1  --------  3
2  --------  2
4  --------  4
4  --------  4
0  --------  3
0  --------  0
3  --------  0
0  --------  0
0  --------  0
1  --------  1
5  --------  5
3  --------  3
0  --------  0
0  --------  0
1  --------  1
3  --------  0
0  --------  2
0  --------  0
1  --------  1
1  --------  1
0  --------  0
6  --------  6
0  --------  0
0  --------  0
0  --------  5
0  --------  1
0  --------  0
0  --------  0
0  --------  4
4  --------  4
3  --------  3
0  --------  0
0  --------  0
0  --------  0
0  --------  0
4  --------  4
0  --------  0
0  --------  0
1  --------  1
0  --------  0
0  --------  1
1  --------  1
1  -------

1  --------  1
1  --------  7
2  --------  2
0  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  1
3  --------  3
0  --------  7
0  --------  0
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
0  --------  2
1  --------  1
0  --------  0
0  --------  0
0  --------  0
4  --------  4
1  --------  1
5  --------  5
2  --------  2
0  --------  0
0  --------  0
0  --------  0
0  --------  0
3  --------  3
0  --------  0
1  --------  1
0  --------  1
1  --------  1
4  --------  4
2  --------  1
3  --------  7
1  --------  5
0  --------  0
0  --------  0
0  --------  0
0  --------  0
3  --------  3
1  --------  1
0  --------  0
0  --------  7
7  --------  7
0  --------  0
2  --------  0
1  --------  1
0  --------  0
1  --------  1
2  --------  2
3  --------  3
1  --------  4
0  --------  3
1  --------  1
7  --------  7
0  --------  0
3  --------  3
0  --------  1
1  --------  1
1  --------  1
0  --------  4
0  --------  0
1  --------  1
0  -------

0  --------  2
4  --------  4
2  --------  4
3  --------  3
5  --------  5
1  --------  1
0  --------  0
1  --------  1
1  --------  5
2  --------  2
1  --------  1
6  --------  6
3  --------  0
2  --------  2
1  --------  1
1  --------  7
1  --------  0
5  --------  5
3  --------  3
1  --------  1
2  --------  0
2  --------  2
1  --------  1
0  --------  1
5  --------  1
2  --------  0
6  --------  6
0  --------  0
1  --------  1
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  4
0  --------  0
2  --------  5
0  --------  0
3  --------  7
0  --------  0
2  --------  0
2  --------  2
1  --------  1
0  --------  0
0  --------  0
0  --------  0
1  --------  0
0  --------  1
0  --------  0
0  --------  0
3  --------  1
3  --------  3
0  --------  0
0  --------  1
0  --------  0
3  --------  3
3  --------  3
0  --------  0
1  --------  0
1  --------  1
0  --------  0
4  --------  4
2  --------  2
2  --------  0
0  -------

2  --------  2
3  --------  5
0  --------  0
1  --------  1
1  --------  1
0  --------  0
0  --------  0
2  --------  3
0  --------  0
1  --------  1
0  --------  2
0  --------  0
0  --------  2
4  --------  4
2  --------  2
0  --------  0
0  --------  0
3  --------  3
1  --------  1
1  --------  1
4  --------  4
1  --------  1
1  --------  5
1  --------  1
1  --------  1
1  --------  1
0  --------  0
2  --------  2
2  --------  2
0  --------  0
3  --------  3
0  --------  0
1  --------  1
0  --------  3
1  --------  1
1  --------  0
5  --------  5
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  4
0  --------  0
3  --------  3
2  --------  2
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  0
3  --------  3
0  --------  0
0  --------  0
3  --------  3
0  --------  0
1  --------  1
0  --------  0
0  --------  2
0  --------  0
1  --------  1
0  --------  0
1  --------  1
1  --------  1
0  --------  0
1  --------  1
1  --------  1
1  -------

1  --------  1
0  --------  0
0  --------  3
2  --------  2
0  --------  0
3  --------  1
2  --------  2
1  --------  0
0  --------  0
1  --------  1
3  --------  7
0  --------  0
1  --------  1
5  --------  5
2  --------  2
0  --------  0
0  --------  0
0  --------  3
3  --------  7
0  --------  0
1  --------  5
5  --------  5
1  --------  0
1  --------  5
2  --------  2
0  --------  3
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  1
1  --------  1
0  --------  0
2  --------  3
4  --------  4
1  --------  1
0  --------  0
1  --------  1
1  --------  1
1  --------  1
0  --------  1
3  --------  7
3  --------  0
1  --------  1
1  --------  1
2  --------  2
0  --------  0
3  --------  0
1  --------  1
7  --------  7
0  --------  0
3  --------  3
0  --------  2
0  --------  0
0  --------  2
0  --------  1
1  --------  1
1  --------  1
0  --------  4
0  --------  0
0  --------  0
1  --------  1
0  --------  0
3  --------  3
0  --------  1
0  --------  0
1  -------

3  --------  3
0  --------  0
3  --------  2
4  --------  4
1  --------  1
3  --------  3
0  --------  0
1  --------  1
5  --------  5
1  --------  1
3  --------  3
1  --------  1
3  --------  3
0  --------  0
0  --------  1
1  --------  5
1  --------  5
1  --------  1
1  --------  1
0  --------  0
0  --------  0
1  --------  4
1  --------  1
3  --------  3
0  --------  0
0  --------  0
0  --------  0
1  --------  1
1  --------  1
0  --------  3
2  --------  7
6  --------  6
2  --------  2
0  --------  1
0  --------  0
0  --------  0
0  --------  0
0  --------  0
3  --------  6
1  --------  1
0  --------  0
2  --------  2
1  --------  1
1  --------  1
0  --------  0
3  --------  3
2  --------  2
1  --------  5
2  --------  2
1  --------  1
3  --------  3
1  --------  1
1  --------  1
0  --------  0
0  --------  0
3  --------  0
0  --------  3
0  --------  0
2  --------  4
0  --------  0
1  --------  1
0  --------  1
1  --------  1
0  --------  0
0  --------  0
0  --------  1
6  -------

3  --------  7
1  --------  1
1  --------  1
0  --------  0
0  --------  0
0  --------  0
5  --------  5
3  --------  3
2  --------  2
0  --------  0
0  --------  0
0  --------  3
2  --------  2
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
0  --------  0
0  --------  0
5  --------  0
0  --------  0
0  --------  0
2  --------  2
3  --------  5
2  --------  0
3  --------  3
1  --------  1
1  --------  1
0  --------  0
4  --------  0
0  --------  1
0  --------  0
0  --------  0
4  --------  4
0  --------  0
1  --------  3
0  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  5
1  --------  1
0  --------  2
0  --------  0
3  --------  3
0  --------  0
0  --------  0
0  --------  0
7  --------  1
0  --------  0
0  --------  0
1  --------  1
5  --------  5
1  --------  5
0  --------  0
1  --------  1
0  --------  0
0  --------  0
0  --------  0
1  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  1
0  --------  0
0  -------

0  --------  0
0  --------  0
0  --------  0
0  --------  0
3  --------  7
0  --------  0
0  --------  0
0  --------  7
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  7
4  --------  4
0  --------  0
0  --------  0
5  --------  5
2  --------  2
4  --------  4
1  --------  1
0  --------  0
0  --------  3
0  --------  0
5  --------  5
0  --------  0
3  --------  3
3  --------  3
1  --------  1
0  --------  0
0  --------  0
1  --------  1
2  --------  2
1  --------  1
1  --------  1
3  --------  3
2  --------  2
1  --------  7
1  --------  1
3  --------  2
2  --------  2
1  --------  3
0  --------  0
0  --------  0
1  --------  1
4  --------  4
2  --------  2
0  --------  0
0  --------  0
0  --------  0
5  --------  5
5  --------  5
3  --------  0
0  --------  0
1  --------  1
3  --------  2
1  --------  1
1  --------  1
0  --------  0
1  --------  1
0  --------  2
1  --------  1
1  --------  5
0  --------  0
0  --------  0
2  --------  2
5  --------  5
4  -------

0  --------  0
1  --------  1
1  --------  1
1  --------  1
1  --------  1
1  --------  1
0  --------  0
0  --------  5
1  --------  1
2  --------  2
0  --------  0
0  --------  1
5  --------  5
1  --------  1
1  --------  1
2  --------  2
1  --------  1
1  --------  4
1  --------  1
0  --------  0
1  --------  1
3  --------  3
1  --------  3
2  --------  2
0  --------  0
2  --------  2
2  --------  2
7  --------  7
0  --------  0
0  --------  0
1  --------  5
1  --------  1
5  --------  5
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  1
1  --------  1
4  --------  4
3  --------  7
0  --------  0
1  --------  1
1  --------  1
0  --------  0
0  --------  0
1  --------  1
1  --------  3
3  --------  0
0  --------  0
5  --------  1
3  --------  3
1  --------  6
1  --------  0
3  --------  3
1  --------  1
1  --------  1
1  --------  0
4  --------  4
1  --------  1
0  --------  3
0  --------  0
0  -------

1  --------  1
1  --------  1
0  --------  0
0  --------  0
0  --------  0
2  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
2  --------  2
0  --------  0
3  --------  3
1  --------  7
0  --------  0
7  --------  7
1  --------  1
0  --------  0
1  --------  1
0  --------  0
0  --------  1
0  --------  0
1  --------  1
3  --------  0
5  --------  5
1  --------  5
1  --------  1
0  --------  0
1  --------  1
0  --------  0
1  --------  1
1  --------  1
0  --------  3
1  --------  1
0  --------  0
0  --------  0
5  --------  5
3  --------  0
1  --------  3
1  --------  1
4  --------  4
0  --------  0
5  --------  2
1  --------  1
3  --------  3
2  --------  2
0  --------  5
0  --------  1
1  --------  1
1  --------  0
2  --------  0
1  --------  3
1  --------  1
0  --------  0
1  --------  1
1  --------  1
0  --------  2
1  --------  1
0  --------  0
0  --------  0
1  --------  1
1  --------  5
5  --------  5
1  --------  0
0  --------  0
1  --------  1
0  -------

0  --------  0
2  --------  2
0  --------  0
5  --------  5
4  --------  4
0  --------  0
0  --------  0
0  --------  0
1  --------  1
1  --------  1
4  --------  4
1  --------  5
0  --------  0
1  --------  1
3  --------  0
0  --------  0
6  --------  6
0  --------  0
1  --------  1
0  --------  7
0  --------  1
0  --------  2
0  --------  0
0  --------  0
1  --------  1
1  --------  1
3  --------  3
1  --------  1
1  --------  1
0  --------  0
0  --------  0
1  --------  1
6  --------  6
3  --------  3
2  --------  2
1  --------  1
0  --------  0
1  --------  1
0  --------  0
1  --------  1
4  --------  0
0  --------  0
0  --------  0
0  --------  4
0  --------  0
1  --------  1
1  --------  1
0  --------  0
1  --------  1
0  --------  0
4  --------  4
3  --------  3
2  --------  2
5  --------  5
0  --------  0
2  --------  2
0  --------  0
0  --------  0
1  --------  1
0  --------  0
0  --------  0
0  --------  0
4  --------  4
2  --------  2
0  --------  0
0  --------  0
4  -------

2  --------  2
1  --------  1
1  --------  1
2  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  2
3  --------  3
0  --------  0
1  --------  5
1  --------  1
0  --------  0
6  --------  6
3  --------  5
0  --------  0
0  --------  0
4  --------  4
0  --------  0
3  --------  0
3  --------  3
5  --------  5
1  --------  1
0  --------  0
0  --------  0
0  --------  0
1  --------  1
3  --------  6
1  --------  1
1  --------  1
1  --------  1
1  --------  1
6  --------  6
0  --------  0
0  --------  1
0  --------  0
0  --------  0
5  --------  5
0  --------  0
0  --------  0
0  --------  1
1  --------  0
3  --------  3
0  --------  0
2  --------  1
1  --------  1
1  --------  1
0  --------  1
1  --------  1
3  --------  3
1  --------  1
1  --------  1
0  --------  0
1  --------  1
0  --------  0
1  --------  6
1  --------  1
0  --------  0
2  --------  2
0  --------  0
1  --------  4
1  --------  1
2  --------  2
1  --------  1
1  --------  3
4  --------  4
1  -------

1  --------  1
3  --------  0
0  --------  0
0  --------  0
0  --------  0
4  --------  4
0  --------  0
0  --------  0
1  --------  0
2  --------  2
0  --------  0
0  --------  0
0  --------  3
0  --------  0
2  --------  2
1  --------  4
1  --------  1
1  --------  4
1  --------  0
2  --------  2
0  --------  0
0  --------  2
1  --------  1
0  --------  0
0  --------  0
1  --------  4
0  --------  0
7  --------  7
0  --------  0
1  --------  1
6  --------  6
0  --------  0
2  --------  2
0  --------  0
0  --------  0
0  --------  0
0  --------  0
3  --------  7
3  --------  0
0  --------  1
2  --------  0
0  --------  0
3  --------  0
3  --------  3
2  --------  2
3  --------  1
1  --------  1
0  --------  0
3  --------  3
6  --------  6
4  --------  4
4  --------  4
1  --------  1
0  --------  0
6  --------  6
0  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  0
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  1
0  -------

3  --------  3
0  --------  0
0  --------  3
0  --------  0
2  --------  2
5  --------  5
4  --------  4
1  --------  1
0  --------  0
0  --------  0
1  --------  1
1  --------  1
1  --------  1
0  --------  0
0  --------  0
0  --------  0
1  --------  1
0  --------  0
1  --------  1
0  --------  0
3  --------  3
3  --------  2
1  --------  1
0  --------  0
1  --------  5
1  --------  4
0  --------  4
0  --------  1
0  --------  0
0  --------  0
2  --------  2
0  --------  0
6  --------  6
0  --------  0
1  --------  2
1  --------  0
0  --------  0
3  --------  1
0  --------  0
0  --------  0
3  --------  1
6  --------  6
2  --------  2
1  --------  1
4  --------  4
0  --------  0
2  --------  3
1  --------  1
1  --------  1
3  --------  3
3  --------  7
6  --------  6
1  --------  1
0  --------  0
0  --------  0
3  --------  3
0  --------  0
1  --------  1
3  --------  0
1  --------  1
0  --------  0
0  --------  0
0  --------  0
0  --------  0
0  --------  6
0  --------  0
0  -------

4  --------  4
1  --------  1
0  --------  0
2  --------  2
5  --------  5
0  --------  0
0  --------  0
1  --------  1
7  --------  7
0  --------  2
2  --------  4
2  --------  0
4  --------  4
0  --------  0
1  --------  1
0  --------  0
1  --------  1
2  --------  2
1  --------  1
1  --------  4
3  --------  3
0  --------  0
0  --------  1
0  --------  0
0  --------  0
0  --------  0
2  --------  2
4  --------  4
6  --------  6
1  --------  1
0  --------  0
0  --------  0
2  --------  2
3  --------  3
0  --------  0
4  --------  4
0  --------  0
1  --------  0
1  --------  3
0  --------  0
1  --------  1
1  --------  1
1  --------  1
1  --------  1
2  --------  2
1  --------  1
4  --------  4
0  --------  0
1  --------  1
0  --------  0
1  --------  1
0  --------  0
2  --------  0
4  --------  4
5  --------  5
0  --------  1
2  --------  2
0  --------  0
1  --------  2
4  --------  4
0  --------  0
0  --------  0
4  --------  4
2  --------  2
4  --------  4
3  --------  7
0  -------

In [54]:
# measuring accuracy
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)

0.8077561305389958

In [55]:
# confusion matrix
confusion_matrix = metrics.confusion_matrix(y_test,y_pred_class)
print(confusion_matrix)

[[5877  233  274  133   18    6    3    4]
 [ 376 3722   17   44   39   40    3    6]
 [ 274   52 1288   43    4   13    6    4]
 [ 237   92   41  784   13    7    0   13]
 [  76  137   41   16  704    1    2    0]
 [  45  266   31   20    6  402    5    1]
 [  58   69   12   29    7   10  249    2]
 [  79   76   18  115    4    5    2  117]]


In [ ]:
confusion_matrix.shape

In [ ]:
# 'POLITICS':0,
# 'ENTERTAINMENT':1,
# 'WORLDNEWS':2,         
# 'BUSINESS':3,          
# 'SPORTS':4,            
# 'ARTS_CULTURE':5,      
# 'SCIENCE':6,           
# 'TECH':7

In [ ]:
import seaborn as sns;
heat_map = sns.heatmap(confusion_matrix,cmap="YlGnBu",
                       xticklabels=["POLITICS","ENTERTAINMENT","WORLDNEWS","BUSINESS","SPORTS","ArtsC","Science","TECH"],
                       yticklabels=["POLITICS","ENTERTAINMENT","WORLDNEWS","BUSINESS","SPORTS","ArtsC","Science","TECH"])

In [ ]:
n_m = confusion_matrix / confusion_matrix.astype(np.float).sum(axis=1)

In [ ]:
clean_n_m=(np.around(n_m,decimals=3))
clean_n_m

In [ ]:
import seaborn as sns;

heat_map = sns.heatmap(clean_n_m,cmap="YlGnBu",
                       xticklabels=["POLITICS","ENTERTAINMENT","WORLDNEWS","BUSINESS","SPORTS","ArtsC","Science","TECH"],
                       yticklabels=["POLITICS","ENTERTAINMENT","WORLDNEWS","BUSINESS","SPORTS","ArtsC","Science","TECH"])

# My test

In [4]:
doc= ["Patriots' Cardona promoted to lieutenant in Navy Joe Cardona, who has spent his entire NFL career with the Patriots balancing his football and active-duty commitments, has been promoted to the rank of lieutenant in the U.S. Navy."]

In [57]:
docx = cvec.transform(doc)

In [61]:
print(docx)

  (0, 1363)	1
  (0, 4024)	1
  (0, 7300)	2
  (0, 7306)	1
  (0, 9224)	1
  (0, 13857)	1
  (0, 14849)	1
  (0, 17059)	1
  (0, 23550)	1
  (0, 25669)	2
  (0, 29751)	2
  (0, 30079)	1
  (0, 32297)	2
  (0, 34521)	2
  (0, 35468)	1
  (0, 41229)	1


In [59]:
docp = NBmodel.predict(docx)
docp

array([4])

In [68]:
# Pipeplines 
from sklearn.pipeline import Pipeline
myNBmodel = Pipeline([('cvec',CountVectorizer(stop_words="english")),
                       ('clf',MultinomialNB()),
                     ])

In [69]:
myNBmodel.fit(strat_train_set.data,y_train)

Pipeline(memory=None,
         steps=[('cvec',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words='english', strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('clf',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [72]:
y_pred_class = myNBmodel.predict(strat_test_set.data)

In [73]:
# measuring accuracy
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)

0.8077561305389958

In [70]:
p =myNBmodel.predict(doc)

In [1]:
import pickle

In [73]:
# Saving model to disk
pickle.dump(myNBmodel, open('myNBmodel.pkl','wb'))


In [2]:

# Loading model to compare the results
myNBmodel = pickle.load( open('myNBmodel.pkl','rb'))

/home/felladog/.local/share/virtualenvs/BreakFast-vYJ3fvFQ/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.20.1 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/felladog/.local/share/virtualenvs/BreakFast-vYJ3fvFQ/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator MultinomialNB from version 0.20.1 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/felladog/.local/share/virtualenvs/BreakFast-vYJ3fvFQ/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator Pipeline from version 0.20.1 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [5]:
myNBmodel.predict(doc)

array([4])

#  TfidfTransformer



In [95]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline


In [96]:
myTmodel = Pipeline([('cvec',CountVectorizer(stop_words="english")),
                       ('tfidf', TfidfTransformer()),
                       ('clf',MultinomialNB()),
                     ])

In [97]:
myTmodel.fit(strat_train_set.data,y_train)

Pipeline(memory=None,
         steps=[('cvec',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words='english', strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [98]:
y_pred_class=myTmodel.predict(strat_test_set.data)

In [55]:
y_pred_class

array([0, 0, 0, ..., 0, 0, 1])

In [99]:
# measuring accuracy
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)

0.6718087394751399

In [100]:
# confusion matrix
confusion_matrix = metrics.confusion_matrix(y_test,y_pred_class)
print(confusion_matrix)

[[6385  133   26    2    2    0    0    0]
 [ 669 3574    3    1    0    0    0    0]
 [1035   65  583    1    0    0    0    0]
 [ 997   89    6   91    4    0    0    0]
 [ 419  339   13    1  205    0    0    0]
 [ 235  471   12    3    0   55    0    0]
 [ 253  145   10    0    0    0   28    0]
 [ 289  109    1    7    0    0    0   10]]


# Linear Support Vector Machine

In [107]:
# from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC


sv = Pipeline([('vect', CountVectorizer(stop_words="english")),
                ('tfidf', TfidfTransformer()),
                ('clf',LinearSVC()),
               ])

In [108]:
sv.fit(strat_train_set.data,y_train)

Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words='english', strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                

In [109]:
y_pred_class=sv.predict(strat_test_set.data)

In [110]:
# measuring accuracy
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)

0.8228750537766578

In [111]:
# measuring accuracy
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)

0.8228750537766578

In [112]:
# confusion matrix
confusion_matrix = metrics.confusion_matrix(y_test,y_pred_class)
print(confusion_matrix)

[[5884  218  248  114   29   21   17   17]
 [ 302 3693   24   45   62   83   16   22]
 [ 289   50 1265   34   12   18    9    7]
 [ 215   85   44  769   14   11    4   45]
 [  58   91   29   13  778    3    3    2]
 [  50  183   28   13    9  479    8    6]
 [  47   45   11    6    6   10  306    5]
 [  53   50   21   55    8    6    8  215]]
